-- setup_script.sql: Snowflake Native App Installation Setup Script
CREATE APPLICATION ROLE IF NOT EXISTS AUTOMOTIVE_APP_ADMIN;

CREATE SCHEMA IF NOT EXISTS CORE;
GRANT USAGE ON SCHEMA CORE TO APPLICATION ROLE AUTOMOTIVE_APP_ADMIN;

-- Create Streamlit Application instance inside Native App
CREATE STREAMLIT IF NOT EXISTS CORE.APP_INSTANCE
  FROM '/streamlit'
  MAIN_FILE = 'app.py';

GRANT USAGE ON STREAMLIT CORE.APP_INSTANCE TO APPLICATION ROLE AUTOMOTIVE_APP_ADMIN;
